"""Driven subsonic hydrodynamic turbulence in AthenaK (PLM + Roe, 2nd order).

The AthenaK half of the two-code convergence study; see ``driven_turbulence.py``
for the astronomix half and for how the two forcing implementations are matched.
This script writes an ``athinput`` for the built-in ``turb`` problem generator
and runs the pre-built A100 binary, dumping ``.bin`` snapshots that ``spectra.py``
reads back.

Notes on the AthenaK configuration:

    - ``eos = isothermal`` keeps the Mach number fixed over the whole run (an
      ideal-gas box heats up as the injected energy thermalises, so M drifts
      down by ~20% over ten turnovers).
    - AthenaK forbids ``hllc`` with an isothermal EOS, so the default here is
      ``roe`` — the *least* diffusive 2nd-order option available, which is the
      fair choice against astronomix's characteristic-wise WENO5. Use
      ``--rsolver hlle`` for the more diffusive control run.
    - ``cfl_number = 0.3`` matches astronomix's ``C_cfl = 0.9`` (the two codes
      normalise the 3D CFL condition differently; see driven_turbulence.py).

    python examples/scripts/forward/hydro/turbulence/athenak_turb.py --n 128
"""

# general
import argparse
import shutil
import subprocess
import sys
import time as walltime
from pathlib import Path

# numerics
import numpy as np

HERE = Path(__file__).resolve().parent
RUN_ROOT = Path("/export/data/lstorcks/turb_spectra")
#: The ``turb`` problem generator lives in ``src/pgen/fluids/`` and is NOT part of
#: AthenaK's ``built_in_pgens`` set, so it needs its own build:
#:   cmake -S . -B build-turb -D Kokkos_ENABLE_CUDA=On \
#:         -D Kokkos_ARCH_AMPERE80=On -D PROBLEM=fluids/turb \
#:         -D CMAKE_CXX_COMPILER=<athenak>/kokkos/bin/nvcc_wrapper \
#:         -D CMAKE_CXX_FLAGS="-I<athenak>/src/pgen"
#: (the last flag is needed because ``fluids/turb.cpp`` includes ``pgen.hpp``
#: as if it sat one directory up).
ATHENAK_BIN = Path("/export/home/lstorcks/athena/athenak/build-turb/src/athena")

#: Shared physical setup — must stay in sync with driven_turbulence.py.
BOX_SIZE = 1.0
RHO0 = 1.0
CS = 1.0


ATHINPUT = """\
# Driven subsonic isothermal hydrodynamic turbulence — astronomix/AthenaK
# spectral convergence study (generated by athenak_turb.py, do not edit).

<comment>
problem   = subsonic driven turbulence

<job>
basename  = Turb

<mesh>
nghost    = 2
nx1       = {n}
x1min     = -0.5
x1max     = 0.5
ix1_bc    = periodic
ox1_bc    = periodic

nx2       = {n}
x2min     = -0.5
x2max     = 0.5
ix2_bc    = periodic
ox2_bc    = periodic

nx3       = {n}
x3min     = -0.5
x3max     = 0.5
ix3_bc    = periodic
ox3_bc    = periodic

<meshblock>
nx1       = {mb}
nx2       = {mb}
nx3       = {mb}

<time>
evolution  = dynamic
integrator = rk2
cfl_number = {cfl}
nlim       = -1
tlim       = {tlim}
ndiag      = 1000

<hydro>
eos             = isothermal
iso_sound_speed = {cs}
reconstruct     = plm
rsolver         = {rsolver}

<problem>
d_n = {rho0}

<turb_driving>
type  = hydro
tcorr = {tcorr}
dedt  = {dedt}
nlow  = {nlow}
nhigh = {nhigh}
expo  = {expo}

<output1>
file_type = hst
dt        = {hst_dt}

<output2>
file_type = bin
variable  = hydro_w
dt        = {snap_dt}
"""


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--n", type=int, default=128, help="cells per dimension")
    p.add_argument("--mach", type=float, default=0.3, help="target turbulent Mach number")
    p.add_argument("--dedt", type=float, default=-1.0,
                   help="energy injection rate; <0 uses the v_rms^3 / (2 L) estimate")
    p.add_argument("--calibrated", action="store_true",
                   help="take dedt from data/athenak_dedt_calibration.json, which "
                        "calibrate_athenak.py tunes per resolution so every run sits "
                        "at the same Mach number as astronomix (AthenaK's dedt is not "
                        "a resolution-invariant control; see check_athenak_driving.py)")
    p.add_argument("--tcorr", type=float, default=-1.0,
                   help="OU correlation time; 0 = white-in-time driving; "
                        "<0 uses L / (2 pi v_rms)")
    p.add_argument("--nlow", type=int, default=1)
    p.add_argument("--nhigh", type=int, default=2)
    p.add_argument("--expo", type=float, default=5.0 / 3.0)
    p.add_argument("--nturn", type=float, default=10.0,
                   help="run length in large-eddy turnover times L / (2 v_rms)")
    p.add_argument("--nsnap", type=int, default=41)
    p.add_argument("--cfl", type=float, default=0.3)
    p.add_argument("--rsolver", choices=["roe", "hlle", "llf"], default="roe")
    p.add_argument("--mb", type=int, default=0,
                   help="meshblock size; 0 = one block covering the whole mesh")
    p.add_argument("--tag", type=str, default="")
    p.add_argument("--dry-run", action="store_true", help="write the athinput and stop")
    args = p.parse_args()

    v_target = args.mach * CS
    if args.calibrated:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from calibrate_athenak import load_calibration
        cal = load_calibration()
        if str(args.n) not in cal:
            raise SystemExit(f"no calibration for N={args.n}; "
                             f"run calibrate_athenak.py --n {args.n} first")
        dedt = float(cal[str(args.n)]["dedt"])
    else:
        dedt = args.dedt if args.dedt > 0 else v_target ** 3 / (2.0 * BOX_SIZE)
    # tcorr = 0 selects turb_driver's whitenoise branch (its `tcorr <= 1e-6`
    # test), where the applied field IS the field the dedt normalisation was
    # computed from. That makes the per-step injection exactly dedt*dt, but it
    # does NOT make the stationary Mach number resolution-independent — measured,
    # the white branch drifts more than the OU one, so the production runs use OU
    # driving with a per-resolution dedt calibration instead.
    tcorr = args.tcorr if args.tcorr >= 0 else BOX_SIZE / (2.0 * np.pi * v_target)
    t_turnover = BOX_SIZE / (2.0 * v_target)
    tlim = args.nturn * t_turnover

    tag = args.tag or f"n{args.n}"
    if args.rsolver != "roe":
        tag = f"{tag}_{args.rsolver}"
    rundir = RUN_ROOT / tag
    if rundir.exists():
        shutil.rmtree(rundir)
    (rundir / "bin").mkdir(parents=True, exist_ok=True)

    text = ATHINPUT.format(
        n=args.n, mb=(args.mb or args.n), cfl=args.cfl, tlim=tlim, cs=CS,
        rsolver=args.rsolver, rho0=RHO0, tcorr=tcorr, dedt=dedt,
        nlow=args.nlow, nhigh=args.nhigh, expo=args.expo,
        hst_dt=tlim / 400.0, snap_dt=tlim / (args.nsnap - 1),
    )
    inp = rundir / "turb.athinput"
    inp.write_text(text)
    print(f"[athenak-turb] N={args.n}^3  target Mach={args.mach}  rsolver={args.rsolver}")
    print(f"[athenak-turb] dedt={dedt:.6g}  tcorr={tcorr:.4f}  band n=[{args.nlow},{args.nhigh}]")
    print(f"[athenak-turb] t_turnover={t_turnover:.4f}  tlim={tlim:.4f}  -> {rundir}")
    if args.dry_run:
        return

    if not ATHENAK_BIN.exists():
        raise SystemExit(f"AthenaK binary not found: {ATHENAK_BIN}")

    t0 = walltime.perf_counter()
    proc = subprocess.run(
        [str(ATHENAK_BIN), "-i", str(inp), "-d", str(rundir)],
        cwd=rundir, capture_output=True, text=True,
    )
    runtime = walltime.perf_counter() - t0
    (rundir / "stdout.log").write_text(proc.stdout)
    (rundir / "stderr.log").write_text(proc.stderr)
    if proc.returncode != 0:
        print(proc.stdout[-4000:])
        print(proc.stderr[-4000:])
        raise SystemExit(f"AthenaK exited {proc.returncode}")

    # Record the metadata spectra.py needs alongside the .bin dumps.
    np.savez(
        rundir / "meta.npz",
        n=args.n, box_size=BOX_SIZE, cs=CS, dedt=dedt, tcorr=tcorr,
        nlow=args.nlow, nhigh=args.nhigh, expo=args.expo,
        t_turnover=t_turnover, runtime=runtime, rsolver=args.rsolver,
        label=f"AthenaK (PLM+{args.rsolver.upper()}, 2nd order)",
    )
    ndump = len(list((rundir / "bin").glob("*.bin")))
    print(f"[athenak-turb] runtime {runtime:.1f} s, {ndump} dumps -> {rundir}")


if __name__ == "__main__":
    main()
